# 5. Ingress Resource with TLS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hostname-ingress
  namespace: demoapp
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: cloud-venafi-issuer
    cert-manager.io/common-name: kubeapp.vfidev.com
    cert-manager.io/subject-organizations: Cyberark
    cert-manager.io/subject-organizationalunits: IT
    cert-manager.io/subject-countries: IN
    cert-manager.io/subject-provinces: KA
    cert-manager.io/subject-localities: Bangalore
    cert-manager.io/duration: 48h
spec:
  tls:
  - hosts:
    - kubeapp.vfidev.com
    secretName: kubeapp-tls-secret
  rules:
  - host: kubeapp.vfidev.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hostname-service
            port:
              number: 80