apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloud-venafi-issuer
  namespace: demoapp
spec:
  venafi:
    zone: "kube-app\\kube-iss-template"
    cloud:
      url: https://api.venafi.eu/
      apiTokenSecretRef:
        name: cloud-secret
        key: apikey